### ISSUE TITLE
RequestString seems hangs on Linux(Mono) with some urls

### ISSUE THREAD

**Issue by ed-ilyin** [fsprojects/FSharp.Data#1021]
The following code seems just hangs on Linux (or maybe Mono) with this specific url.
```fsharp
#r @"../../packages/FSharp.Data/lib/net40/FSharp.Data.dll"
FSharp.Data.Http.RequestString "https://marketplacetest.ccpaas.net"
```
It is posible to interrupt hby Ctrl+C

Same code and url works on Windows.

How can I solve or workaround this problem?

**Comment by ovatsus** [comment]
Does this still happen on Mono 5?

**Comment by dsyme** [comment]
Closing out mono-specific things
