### ISSUE TITLE
Add cssSelect to HtmlNode

### ISSUE THREAD

**Issue by eugbaranov** [fsprojects/FSharp.Data#1096]
If we move/add `cssSelect` to `HtmlNode` then we could enable better type inference when working with nodes in functions:
```fsharp
node |> HtmlNode.cssSelect "tr"
```

**Comment by ovatsus** [comment]
you can do `node.CssSelect "tr"` already. See https://github.com/fsharp/FSharp.Data/blob/c074d945d6dfa59d3749b527f96b2356ab17a0a4/src/Html/HtmlCssSelectors.fs#L394

**Comment by Regent** [comment]
I get it, but wouldn't it be more functional if added to `HtmlNode`?
Right now, if I want a function doing something with `HtmlNode` based on `CssSelect` I would have to explicitly specify the type.

**Comment by ovatsus** [comment]
Sure, you can send a PR adding that

**Comment by Regent** [comment]
I've looked at it another day and found it to be not as trivial as I hoped it to be, unless we move `CssSelectorExtensions` into `HtmlNode` which I'm not sure is something we want to do.

**Comment by ovatsus** [comment]
Yes, it's a bit tricky. I guess you could merge HtmlCssSelectors.fs with HtmlOperations.fs
