### ISSUE TITLE
The http module cannot access some websites

### ISSUE THREAD

**Issue by nkw** [fsprojects/FSharp.Data#1190]
The details can be found in [https://stackoverflow.com/questions/51714017/fsharp-data-http-cannot-handle-302-redirect-when-running-in-net-core-2-1](url)

**Comment by AustinTSchaffer** [comment]
This link no longer redirects anywhere useful.

**Comment by AustinTSchaffer** [comment]
https://stackoverflow.com/questions/51714017/fsharp-data-http-cannot-handle-302-redirect-when-running-in-net-core-2-1

**Comment by masoodrb** [comment]
It looks like above stackoverflow post was removed by their mods. Can't find a context now.

**Comment by cartermp** [comment]
I'll close this out - without any reliable repro it's not valuable to have it open.
