### ISSUE TITLE
InferColumnTypes cannot set empty string as missingValues

### ISSUE THREAD

**Issue by zyzhu** [fsprojects/FSharp.Data#1192]
**Repro steps**
sample.csv, c3 column is all empty
```
row,c1,c2,c3
1,,5,
2,4,6,
```

The following lines tried to infer the types of columns. I set missingValues parameter as `[|""|]`
```fsharp
[<Literal>]
let sample = "C:/FSharp/sample.csv"
let r = CsvFile.Load(sample)
let rTypes = r.InferColumnTypes(2,[|""|],System.Globalization.CultureInfo.GetCultureInfo(""), null, false, false)
rTypes.[3].InferedType.Name
```

**Expected outcome**
```fsharp
val it : string = "Double"
```

**Actual outcome**
```fsharp
val it : string = "String"
```

**Suggestion**
By digging through code, it is by design as empty string cannot be set as missing value. Empty string will always be treated as string. Can we loose this constraint?
https://github.com/fsharp/FSharp.Data/blob/master/src/Csv/CsvInference.fs#L130

In my use cases, csv files are quite dynamic as I don't have a fixed set of column names and column numbers. Hence schema setting won't work for me.

I'm using Deedle's Frame.ReadCsv to load csv file into data frame. But Deedle's implementation referenced CsvInference directly. I cannot set empty string to be inferred as Double.NaN.

**Comment by Jaygem** [comment]
I'm wondering if correcting this bug is still something?

**Comment by zyzhu** [comment]
@ovatsus Any chance to take another look at my pull? It looks quite intuitive to me by switching two if statements to solve the bug.
