### ISSUE TITLE
Infinite loop in HtmlDocument.Parse

### ISSUE THREAD

**Issue by njlr** [fsprojects/FSharp.Data#1264]
This program will never finish, and takes increasing amounts of memory:

```fsharp
open System
open FSharp.Data

let content =
  """
  Steve Jobs
  steve@apple.com

  Education:
    - Master of Mathematics Honours Computer Science and Combinatorics &
      Optimization. I
      specialized in systems and real-time programming, programming language
      implementation, and mathematical optimization.

  Skills:
    - Proficient in Rust, C++, Scheme, x86(_64) LaTeX,
      (Postgre)SQL, Gurobi, AWS, Google Cloud Platform, .NET (Core), C#,
      Python, low-level profiling and optimization on Linux and Windows.

    - Can do things with Java, Haskell, Clojure,
      Scala, AMPS, redis, OpenGL.

    Instructional support assistant at the School,
    September to January 2010.
      - Started the Java project[3], a custom IDE for students in an
        introductory computer science course.


  """

[<EntryPoint>]
let main argv =
  printfn "%s" "Parsing HTML... "

  let html = HtmlDocument.Parse content

  printfn "%s" "done. "

  0

```

I would expect it to return an "invalid HTML" error.

**Comment by adz** [comment]
Thank you so much for this report.

I've been searching for the cause of spiking memory issues (until process is killed) on a server process, which turns out to be completely gone without using the FsData Html parser. It is part of a larger app, and I didn't suspect this code.

We have determined that the issue occurs when there is an "&" without a corresponding ";" or "<" character.

**Comment by dsyme** [comment]
Would be great to get this fixed, anyone want to take a stab at it?

**Comment by colinbull** [comment]
If this is surrounded in a CData tag does it complete?

**Comment by tomakita** [comment]
Hi @colinbull, are you still working on this?  I think I have a fix, but won't submit a PR if you're on the case already.

**Comment by colinbull** [comment]
I have had a look and have a fix but yet to test. Sorry ran out of time.
Feel free to submit a PR and I can review

Many thanks.

**Comment by tomakita** [comment]
Ok, sounds good.  I'll submit my PR after I've cleaned some things up.  If nothing else, maybe we can compare our approaches -- mine might not be a good way to do it.

**Comment by colinbull** [comment]
Yeah.. no worries. Just mention me in the PR and I’ll look

**Comment by cartermp** [comment]
https://github.com/fsprojects/FSharp.Data/pull/1393
