### ISSUE TITLE
StackOverflowException thrown from HtmlDocument.Load

### ISSUE THREAD

**Issue by markfields** [fsprojects/FSharp.Data#1277]
We're seeing StackOverflowException repeatedly in our production service with our HTML parsing code implicated.  I managed to find a repro that hit StackOverflowException and debugged it to find that the line that throws in that case is a call to `FSharp.Data.HtmlDocument.Load`.

Taking a quick look at the code here, I found a non-tail-recursive call [here ](https://github.com/fsharp/FSharp.Data/blob/49a3bfb22a8955463d7536af1d2df86449e335c6/src/Html/HtmlParser.fs#L810) in `parse'` under `HtmlDocument.Load`.  Next step will be to download the source code and load symbols for `FSharp.Data` and see what the callstack is.

The test case that triggered this in our production-like test environment is a `p` tag containing 4090 nested `span` tags:
[4090depth.txt](https://github.com/fsharp/FSharp.Data/files/3448523/4090depth.txt)

This doesn't repro in our dev environment, so there may be some runtime configuration in prod that adjusts the max stack size?  At any rate, using tail recursion everywhere will preclude this kind of bug altogether.

**Comment by markfields** [comment]
I've made (but not yet tested beyond building) a minimally invasive fix, you can see it in #1278 but I need to resubmit the PR from a different fork, so I closed that one.

**Comment by cartermp** [comment]
I will close this since https://github.com/fsprojects/FSharp.Data/pull/1279/ has been merged. Thanks for the contribution!
