### ISSUE TITLE
Http Utilities - Encoding problem

### ISSUE THREAD

**Issue by b0wter** [fsprojects/FSharp.Data#1293]
I am currently facing an issue using `FSharp.Data.Http` to talk to a CouchDb instance. Using `curl` and `Postman` I am receiving properly encoded responses, like this:
```
{
    "_id": "00000000-0000-0000-0000-000000000008",
    "_rev": "1-5e9e6767c8aebeb5748769391716974d",
    "start": "2019-05-05T10:00:00",
    "kind": {
        "id": "00000000-0000-0000-0000-000000000001",
        "name": "SE",
        "abbreviation": "SE",
        "display": {
            "color": {
                "primary": []
            }
        }
    },
    "location": "Düsseldorf",
}
```
However, using `Http.AsyncRequest` the received text seems to not be encoded properly:
```
{
  "id": "00000000-0000-0000-0000-000000000001",
  "name": "SE",
  "abbreviation": "SE",
  "display": {
    "color": {
      "primary": []
    }
  },
  "location": "DÃ¼sseldorf"
}
```
I've attached an image of the response headers:
![postman-headers](https://user-images.githubusercontent.com/614261/68034435-f58c2180-fcc1-11e9-9525-7956e96ea1ea.png)

**Comment by fpellet** [comment]
Encoding is not specify in headers. Default encoding is UTF-8. You can override encoding with `responseEncodingOverride`.

**Comment by b0wter** [comment]
I see. The library doesn't know what kind of encoding to expect since none is returned in the response headers and uses a "fallback" that does not work properly in my case? Thanks for the information!
