### ISSUE TITLE
CSVProvider only prints first column

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Data#1306]
When trying to access members in a csv provider row, I get an error in the FSI. The intellisense however, shows the expected member/field. When printing the rows, only the first column in the csv file is printed.

The code:

```
#I "../../../.paket/load/netstandard2.1/Server"
#load "server.group.fsx"

open System
open System.IO
open FSharp.Data

Environment.CurrentDirectory <- __SOURCE_DIRECTORY__

type Products = FSharp.Data.CsvProvider<"../../../resources/productTypes.csv", CacheRows=false>
type Doses = FSharp.Data.CsvProvider<"../../../resources/doseTypes.csv", CacheRows=false>

let dosePath = Path.Combine(Environment.CurrentDirectory, @"..\..\..\resources/doses.csv")
let doses =
    Doses.Load(dosePath)

for d in doses.Rows do
    printfn "%A" d.Generic

let productPath = Path.Combine(Environment.CurrentDirectory, @"..\..\..\resources/products.csv")
let products =
    Products.Load(productPath)

for p in products.Rows do
    printfn "%A" p


```    

The csv file for the doseTypes:

> Generic,Vorm,Route,Indicatie,Afdeling,Geslacht,MinLeeftijdMnd,MaxLeeftijdMnd,MinGewichtKg,MaxGewichtKg,MinGestDagen,MaxGestDagen,MinPMDagen,MaxPMDagen,Frequenties,Eenheid,NormDose,MinDose,MaxDose,AbsMaxDose,MaxPerDose,DosePerKg,DosePerM2
> abacavir,drank,or,hiv,pediatrie,man,1,12,10,15,234,340,234,340,1 x /week,mg,0.1,0.1,0.1,1.2,1.3,x,x
> 

The screenshot showing intellisense for 'Generic' but failing to run this in the FSI:

![CSVProviderError](https://user-images.githubusercontent.com/683631/74545280-e23b5400-4f48-11ea-8965-e6020eded671.png)

**Comment by dsyme** [comment]
@halcwb If you have time could you try the fix of setting `ResolutionFolder = __SOURCE_DIRECTORY__`?  It looks like it will work

Note the fix at https://github.com/dotnet/fsharp/pull/10866 will not particularly help with this as the implicit ResolutionFolder is still being picked up from the location of the paket load script in `../../../.paket/load/netstandard2.1/Server`.  So you will still need an explicit ResolutionFolder.

I will update the documentation in FSharp.Data to always use `ResolutionFolder = __SOURCE_DIRECTORY__`.

**Comment by halcwb** [comment]
@dsyme Thanks. This has been bothering me for a long time.
