### ISSUE TITLE
Support loading data from JsonValue for JsonProvider.

### ISSUE THREAD

**Issue by voroninp** [fsprojects/FSharp.Data#1309]
JsonProvider supports loading data from uri, stream, and stream reader, but not `JsonValue` which is inconvenient.

Now I had to use it like this:
```FSharp
use ms = new MemoryStream()
use w = new StreamWriter(ms, leaveOpen=false)
value.WriteTo(w, JsonSaveOptions.DisableFormatting)
w.Flush()
ms.Seek(0L, SeekOrigin.Begin) |> ignore
let record = DayCloseData.Load(ms)
```
Instead of just `let record = = DayCloseData.Load(value)`

---
If you a curious why I need this, I can explain. <br/>
Some services return such payload:
```js
{
    "history": {
        "2020-01-10": {
            ...
        },
        "2020-01-11": {
            ...
        }
    }
}
```

**Comment by mlaily** [comment]
I agree that some json cannot be statically parsed and that it would be useful to be able to create an instance from a JsonValue, but note that your workaround can be simplified to `value.ToString() |> DayCloseData.Parse`.
