### ISSUE TITLE
Split out Fsharp.Data.Json.Core etc 

### ISSUE THREAD

**Issue by cartermp** [fsprojects/FSharp.Data#1311]
The support matrix for this package is quite high, which makes adopting updates to things (tools, F# compiler) and contributions tricky and potentially error-prone. I think moving to NS 2.0 only, with a major version bump, might be good for the long-term health of the pakage.

**Comment by pimbrouwers** [comment]
Piggybacking on this, which I completely agree with. Maybe we move away from the single-package, in favor of separate smaller packages. For example: FSharp.Data.Html and FShar.Data.Json as separate packages.

**Comment by pimbrouwers** [comment]
For anyone interested, I've done this specifically for the Json functionality. It was really quite painless.

https://github.com/pimbrouwers/FSharp.Data.JsonValue

**Comment by cartermp** [comment]
@pimbrouwers the FSharp.Data.Json splitting out looks like a great idea. Splitting out each of the type providers would have some benefits:

* Perhaps a bit more clear which one you have
* In line with other packages using FSharp.Data in their name
* If someone is only using one, they are 1/4 less affected by this issue: https://github.com/dotnet/fsharp/issues/7907

However, the downsides are somewhat large. Asking users to move from a single package like this into separate ones is quite a task for the large number of people who depend on this package.

Overall I'd be in favor of that kind of split, but I think more folks involved with this package would have to have a say

**Comment by pimbrouwers** [comment]
@cartermp brilliantly put. I agree on all fronts. 

As far as the migration is concerned, perhaps there could be a deprecation period where the single & multi-package implementations are maintained in parallel. With the understanding that the single package would one day be deprecated.

Perhaps we tackle these problems separately:
- Work toward netstandard2.0 compliance.
- Once established, we can begin teasing apart the tentacles. A separate package for: JSON, HTML, CSV etc.
- Both implementations, single and multi, are maintained in parallel for a period.

**Comment by cartermp** [comment]
Curious what @dsyme thinks here.

**Comment by dsyme** [comment]
I think this would be great

**Comment by CaringDev** [comment]
> ... single & multi-package implementations ...

Or the existing package could be changed to a meta-package referencing all the new ones. This could even be done tentacle by tentacle.

**Comment by joshuapassos** [comment]
It's possible change multi-package ? Is there a roadmap for migration?

**Comment by dsyme** [comment]
I'm renaming this issue to be about splitting out FSharp.Data.Json etc

**Comment by toburger** [comment]
Welcome separation! I often use FSharp.Data solely for it's JSON utility functions.

**Comment by dsyme** [comment]
@pimbrouwers Could you give "fsprojects" ownership of the package "FSharp.Data.Json" please?  We'd potentially like to use it here: #1457 , see https://www.nuget.org/packages/FSharp.Data.Json

**Comment by pimbrouwers** [comment]
Sure thing! Is this the correct method? If so, which account:

![Screenshot_20220815-175138](https://user-images.githubusercontent.com/4595453/184724712-a12b30b1-cb2d-4955-9f35-a242e2ff89c1.png)

**Comment by dsyme** [comment]
@pimbrouwers  The nuget package - I think you add "fsprojects" as org https://www.nuget.org/profiles/fsprojects

**Comment by pimbrouwers** [comment]
@dsyme done!

![Uploading Screenshot_20220815-184700.png…]()

**Comment by pimbrouwers** [comment]
@dsyme done!

![Screenshot_20220815-184700](https://user-images.githubusercontent.com/4595453/184733671-d354fdbe-1cab-4703-9230-cb200f495c61.png)

**Comment by pimbrouwers** [comment]
> A welcome separation! I often use FSharp.Data solely for it's JSON utility functions.

@toburger might be worth checking out [Jay](https://github.com/pimbrouwers/Jay), which is a fork of FSharp.DataJson with some optimizations and refinements. We use it a lot at the NHLPA with great success, you might find it useful as well!

**Comment by dsyme** [comment]
This is now merged and released as FSharp.Data 5.0.1
