### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by cartermp** [fsprojects/FSharp.Data#1339]
Most other type providers that are of shared community interest are in the fsprojects org. The fsprojects org is also more active with respect to:

* A more diverse community of maintainers
* An active set of admins who can shuffle maintainers around as interest in projects increases/decreases

N.B. I'd also be interested in rebooting the build of the provider and its package, but without any kind of rights it's challenging :)

**Comment by dsyme** [comment]
Yup no problem

**Comment by cartermp** [comment]
Wanna initiate the move? I don't have permissions.

**Comment by dsyme** [comment]
Done.

Will need to update docs etc.
