### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by aolney** [fsprojects/FSharp.Data#1345]
README.md is pointing to

http://fsharp.github.io/FSharp.Data/

but should be

https://fsprojects.github.io/FSharp.Data/

Google searches seem to be defaulting to the old link as well

**Comment by dsyme** [comment]
Thanks, fixed in https://github.com/fsprojects/FSharp.Data/pull/1344

We'll need to republish the docs.  

I'll try to chase down other incoming links

**Comment by dsyme** [comment]
There are about 6000 incoming links, I don't see many we can fix.  We could recreate fsharp.github.io/FSharp.Data via an empty gh-pages add a redirect I guess

https://openlinkprofiler.org/r/fsharp.github.io?q=fsharp.github.io&st=0&sq=&dt=0&dq=FSharp.Data&follow=all&trust=all&tt=0&tq=&at=0&aq=&topind=all&ind=all&cat=all&tld=all&special=all&found=0&last=0&sort=0&filter=
