### ISSUE TITLE
Website side-bar links aren't working.

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Data#1368]
Go to the website: https://fsprojects.github.io/FSharp.Data/

Click a side-bar link: https://fsprojects.github.io/FSharp.Data/library/%7B%7Bfsdocs-repository-link%7D%7D

It looks like something to do with changing FSharp.Formatting versions. It appears that some of the Directory build properties / fsdocs shortcuts aren't getting handled correctly.

I can't fix this tonight, but I could take a look in the next couple days.

**Comment by cartermp** [comment]
Ugh, yeah, seems likely. Also the text is cursed: 
![image](https://user-images.githubusercontent.com/6309070/114799372-51c6f200-9d4c-11eb-9bc2-e28328caae9c.png)

**Comment by dsyme** [comment]
I'll get these fixed

**Comment by dsyme** [comment]
https://fsprojects.github.io/FSharp.Formatting/
