### ISSUE TITLE
Docs for HTML provider are broken with Could Not Find Reference ''

### ISSUE THREAD

**Issue by jkone27** [fsprojects/FSharp.Data#1369]
![image](https://user-images.githubusercontent.com/10419217/114864049-d0756b00-9df0-11eb-8ed2-edc512c6d812.png)

**Comment by dsyme** [comment]
Should hopefully be fixed by https://github.com/fsprojects/FSharp.Data/pull/1373 but docs are still refreshing.  Will leave open until we double check

**Comment by cartermp** [comment]
This is resolved now
