### ISSUE TITLE
Question about new dependencies in 4.1.0

### ISSUE THREAD

**Issue by jimfoye** [fsprojects/FSharp.Data#1376]
This version has some new dependencies, but my changed project file just reflects the new version of 4.1.0 for FSharp.Data. So, I don't need to worry about these other packages? I'm targeting .NET Framework 4.7.2.

![image](https://user-images.githubusercontent.com/4249676/116111258-18f81880-a67c-11eb-898f-0fccdde58234.png)

I googled one of these and saw something about support for debugging Nuget binaries, maybe there is a blog post somewhere that succinctly explains all this?

**Comment by baronfel** [comment]
This is an error with the packaging of the nuget package for this project.  The sourcelink dependencies need to be marked as `PrivateAssets=All`, because they are development-time-only dependencies. In this way they will not be pushed on to you as a user.
