### ISSUE TITLE
Multiple record types

### ISSUE THREAD

**Issue by davidsylvestre** [fsprojects/FSharp.Data#1378]
Hello guys, I'm in doubt on how to create a provider for files with multiple records per line.

Data[1]
```
A,1,foo
B,07a0fca2-1b1c-4e44-b1be-c2b05da5afc7,bar
```

The first column of each row represents the type of record and the remaining fields are the data itself.
I thought about reading the lines and directing with a match, but I don't know if it's the best option.
Could you guide me on how to proceed?

[1][https://joshclose.github.io/CsvHelper/examples/reading/reading-multiple-record-types](https://joshclose.github.io/CsvHelper/examples/reading/reading-multiple-record-types/)

**Comment by nhirschey** [comment]
If you want them in the same collection then you'd need to create two providers and then hold them in a discriminated union. Something like what's below. But one Csv type cannot represent two different file formats.

```fsharp
#r "nuget: FSharp.Data"

open FSharp.Data
type A = CsvProvider<"A,1,foo",HasHeaders=false>
type B = CsvProvider<"B,07a0fca2-1b1c-4e44-b1be-c2b05da5afc7,bar",HasHeaders=false>

type AB =
    | A of A.Row
    | B of B.Row

let data = 
    [|"A,1,foo"
      "B,07a0fca2-1b1c-4e44-b1be-c2b05da5afc7,bar"|]

data
|> Seq.map(fun x -> 
    match x.[0] with
    | 'A' -> A (A.ParseRows(x).[0])
    | 'B' -> B (B.ParseRows(x).[0]))

// inferred to be integer
A.GetSample().Rows    
|> Seq.map(fun x -> x.Column2)

// inferred to be guid
B.GetSample().Rows    
|> Seq.map(fun x -> x.Column2)

```

**Comment by davidsylvestre** [comment]
Interesting approach.
It is not really a CSV file, but it is the format that the Brazilian government uses to store tax documents.
The tricky thing is that the types are related by the number of the line.
Here are more details:
[http://sped.rfb.gov.br/estatico/30/5EC21565F41BC9D392045D71E5706429186705/Guia%20Pr%c3%a1tico%20EFD%20-%20Vers%c3%a3o%203.0.6.pdf](http://sped.rfb.gov.br/estatico/30/5EC21565F41BC9D392045D71E5706429186705/Guia%20Pr%c3%a1tico%20EFD%20-%20Vers%c3%a3o%203.0.6.pdf)
