### ISSUE TITLE
Hide test artifacts from GitHub's file indexer

### ISSUE THREAD

**Issue by rdipardo** [fsprojects/FSharp.Data#1380]
GitHub's web UI [is listing HTML](https://github.com/fsprojects?q=&type=&language=html) as this project's primary source language:

![index](https://user-images.githubusercontent.com/59004801/116466958-25779f00-a83d-11eb-8c18-21ab038f671b.png)

You can locally replicate the file stats by running the [github-linguist gem][] inside the working tree:

```
$ github-linguist
86.38%  HTML
13.44%  F#
0.17%   C#
0.00%   Dockerfile
0.00%   Batchfile
0.00%   Shell
```

Passing the `--breakdown` option reveals individual file paths:

```
$ github-linguist  --breakdown

[..omitted..]

HTML:
tests/FSharp.Data.Tests/Data/EmptyDefinitionLists.html
tests/FSharp.Data.Tests/Data/MarketDepth.htm
tests/FSharp.Data.Tests/Data/NuGet.html
tests/FSharp.Data.Tests/Data/SimpleHtmlLists.html
tests/FSharp.Data.Tests/Data/SimpleHtmlTablesWithThead.html
tests/FSharp.Data.Tests/Data/SimpleHtmlTablesWithTr.html
tests/FSharp.Data.Tests/Data/UKDepartures.html
tests/FSharp.Data.Tests/Data/UKLiveProgress.html
tests/FSharp.Data.Tests/Data/doctor_who.html
tests/FSharp.Data.Tests/Data/doctor_who2.html
tests/FSharp.Data.Tests/Data/doctor_who3.html
tests/FSharp.Data.Tests/Data/ebay_cars.htm
tests/FSharp.Data.Tests/Data/imdb_chart.htm
tests/FSharp.Data.Tests/Data/list_of_counties_wikipedia.html
tests/FSharp.Data.Tests/Data/rottentomatoes.html
tests/FSharp.Data.Tests/Data/us_presidents_wikipedia.html
tests/FSharp.Data.Tests/Data/w3c_html_tables.html
tests/FSharp.Data.Tests/Data/wimbledon_wikipedia.html
tests/FSharp.Data.Tests/Data/zoopla.html
tests/FSharp.Data.Tests/Data/zoopla2.html
```

I'm guessing the weighty percentage of HTML depends on SLOC, not file count, since the output omitted above shows a super-majority of F# source files.

As a quick fix, you can add a [specialized rule][] to `.gitattributes`, for example:

```
tests/FSharp.Data.Tests/Data/**.htm* -linguist-detectable
```

Commit the change, then re-check the stats; locally, I get something like:

```
$ github-linguist
98.69%  F#
1.26%   C#
0.02%   Dockerfile
0.02%   Batchfile
0.01%   Shell
```

I'm hesitant about making changes to a core configuration file like `.gitattributes` , so I'll defer the resolution of this issue to someone else, for now.

[github-linguist gem]: https://github.com/github/linguist/
[specialized rule]: https://github.com/github/linguist/blob/master/docs/overrides.md#summary

**Comment by baronfel** [comment]
Luckily I have no such compunctions :)
