### ISSUE TITLE
Excel Spreadsheet type provider?

### ISSUE THREAD

**Issue by jcoliz** [fsprojects/FSharp.Data#1416]
Hi, I was thinking of implementing a type provider for Excel spreadsheets. It would function like the CSV type provider, where the data is expected to be a table with header rows. The advantage of a direct excel spreadsheet provider is that user wouldn't have to export the sheets. User could just work with their data in native form, then load it into their F# app when needed.

It would be based on this: https://github.com/jcoliz/OfficeOpenXMLEasy

Would there be interest in this?

**Comment by sergey-tihon** [comment]
Similar to this one? https://github.com/fsprojects/ExcelProvider

**Comment by jcoliz** [comment]
Nice! Thanks for the pointer.

**Comment by cartermp** [comment]
Closing this since I don't think we'll bring excel data formats into this repo.
