### ISSUE TITLE
HTTP - No need extra newline before the endBoundaryStream in writeMultipart

### ISSUE THREAD

**Issue by kphuanghk** [fsprojects/FSharp.Data#1420]
Regarding #1397 , after introduced newline in MultipartItem stream construction. It should no longer need to have newline before the `endBoundaryStream` . This will cause extra 2 bytes "/r/n" to the last multipart item. 

Original:
```fsharp
        let wholePayload = Seq.append segments [newlineStream(); endBoundaryStream; ]
```
Shall be:
```fsharp
        /// per spec, close-delimiter := "--" boundary "--" CRLF ; no need extra newline
        let wholePayload = Seq.append segments [ endBoundaryStream; ]
```

Here's the skeleton program I used to test the two extra bytes issue:
[TestProgram.fs.MD](https://github.com/fsprojects/FSharp.Data/files/7797880/TestProgram.fs.MD)

 For those affected by this issue, just need to remove extra two bytes for the affected files.

**Comment by cartermp** [comment]
Addressed in https://github.com/fsprojects/FSharp.Data/pull/1421
