### ISSUE TITLE
FSharp.Data namespace conflict with Microsoft.FSharp.Data

### ISSUE THREAD

**Issue by dustysig** [fsprojects/FSharp.Data#1423]
I think I've run into a namespace conflict and I'm not sure how to resolve it in F#. The conflict is between [FSharp.Data](https://www.nuget.org/packages/FSharp.Data/l) and  what I'm assuming is a core part of F#(Microsoft.FSharp.Data)

```
open System
open FSharp.Data

[<Literal>]
let SampleDataFile = __SOURCE_DIRECTORY__ + "/DATA/FILENAME.CSV"
type MyType = FSharp.Data.CsvProvider<SampleDataFile>

CreditCard.GetSample().Rows |> ignore
```

However, when I send this to FSI I get this error, 

`  type MyType = FSharp.Data.CsvProvider<SampleDataFile>
  ------------------------------^^^^^^^^^^^

stdin(6,31): error FS0039: The type 'CsvProvider' is not defined in '**Microsoft.FSharp.Data**'.`

I did the same thing in VS 2019 trying to directly manage the Nuget Packages and references, however this resulted in the same issue. 

Can you advise if there is a way to resolve this?

**Comment by cartermp** [comment]
I don't think you're referencing `FSharp.Data` the package in your environment. This does not reproduce for me:

![image](https://user-images.githubusercontent.com/6309070/148288438-d2988878-b803-40ee-9786-535142025947.png)

That said, if you're preferring to fully qualify all the names for things, you may run into similar issues over time.

**Comment by dustysig** [comment]
Thanks for the reply. 

I assume you are in an .fsx file type? Can you reproduce this in a .fs file?

**Comment by vhogemann** [comment]
I'm seeing the same issue here with FSharp.Data 5.0.2 and JsonProvider on Rider.

**Comment by wilfriedb** [comment]
Not OP, but I can confirm it does happen in a fsx file, but not in a fs file.

**Comment by dsyme** [comment]
Closing as the solution in fsx files it to ad the nuget references

**Comment by dustysig** [comment]
> Closing as the solution in fsx files it to ad the nuget references

Hi, I need this in an .fs file NOT a .fsx.
