### ISSUE TITLE
Tried to build but got a paket exception

### ISSUE THREAD

**Issue by jkone27** [fsprojects/FSharp.Data#1426]
i tried (on macos, vscode, dotnet6 sdk)

```
dotnet fsi ./build.fsx -t Build
``` 
 but got 
 
 error FS3216: Package manager key 'paket' was not registered in [/usr/local/share/dotnet/sdk/5.0.302/FSharp; /usr/local/share/dotnet/sdk/5.0.302/FSharp/], []. Currently registered: nuget
 
 googling for the issue seems related to FAKE
 
 https://stackoverflow.com/questions/66665009/fix-for-package-manager-key-paket-was-not-registered-in-build-fsx
 
 anyone knows how to fix it?

**Comment by jkone27** [comment]
running ./build.sh instead of the .build.fsx as per README seems to work better, so builds fine but with this warnings

```
Warning: Paket resolved a FSharp.Core with version '6.0.0.0', but fake runs with a version of '5.0.0.0'. This is not supported.
Please either lock the version via 'nuget FSharp.Core <nuget-version>' or upgrade fake.
Read https://github.com/fsharp/FAKE/issues/2001 for details.
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.251.0' at the top of your dependencies file (/Users/admin/Repositories/FSharp.Data/paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Warning: The fake-runner has not been updated for at least 12 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
```

**Comment by baronfel** [comment]
you can ignore those warnings, they will go away with the next update of FAKE.

**Comment by cartermp** [comment]
See here for how to build the repo: https://github.com/fsprojects/FSharp.Data/blob/main/README.md#building
