### ISSUE TITLE
CsvProvider fails on Linux (Ubuntu)

### ISSUE THREAD

**Issue by magnushammar** [fsprojects/FSharp.Data#1428]
Edit: It turns out that this had nothing to do with OS but was related to a path problem.  

I tricked myself into thinking that the path was correct as CsvProvider did not complain about not finding the file. Then when doing Stocks.Load I got an instance that partly made sense. This is my excuse, feel free to delete this issue 😁. 

<hr>

This sample works on my Windows machine but not on Linux (Ubuntu 20.04). Both with .Net 6.0

```fsharp 
#r "nuget: FSharp.Data"
open FSharp.Data
type Stocks = CsvProvider<"data/MSFT.csv">
let location = __SOURCE_DIRECTORY__ + "/data/MSFT.csv"
let msft = Stocks.Load(location)
let row = msft.Rows |> Seq.head
row.Open  // The type 'Row' does not define the field, constructor or member 'Open'
```

**Comment by cartermp** [comment]
Pesky paths!
