### ISSUE TITLE
HtmlProvider no longer works with one of the tutorial's sample

### ISSUE THREAD

**Issue by mlaily** [fsprojects/FSharp.Data#1455]
The F1_2017 sample no longer works. This shows on https://fsprojects.github.io/FSharp.Data/library/HtmlProvider.html with an empty output.

Running the fsx file in an IDE actually results in an error:
```fsharp
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.FSharp.Collections.MapTreeModule.throwKeyNotFound[a]() in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 156
   at Microsoft.FSharp.Collections.MapTreeModule.find[TKey,TValue](IComparer`1 comparer, TKey k, MapTree`2 m) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 164
   at FSharp.Data.Runtime.BaseTypes.HtmlTable`1.Create(Func`2 rowConverter, HtmlDocument doc, String id, Boolean hasHeaders) in D:\Data\Dev\Archival-Mess\FSharp.Data\src\Html\HtmlRuntime.fs:line 535
   at <StartupCode$FSI_0034>.$FSI_0034.main@() in D:\Data\Dev\Archival-Mess\FSharp.Data\docs\library\HtmlProvider.fsx:line 85
Stopped due to error
```

After updating the provider sample source with the latest version of the wikipedia page to ensure it's not due to that and after digging a little bit, it seems there is a problem when associating a name to a table.  
Doing it manually shows that all the names generated are suffixed with "Edit":
```fsharp
let url =
  "https://en.wikipedia.org/wiki/" +
    "2017_FIA_Formula_One_World_Championship"

let tables =
    F1_2017.Load(url).Tables.Html
    |> FSharp.Data.Runtime.HtmlRuntime.getTables None true
    |> List.where (fun x -> x.Name.Contains("Season calendar"))
    |> List.map (fun e -> e.Name, e)
    |> Map.ofList
```
![image](https://user-images.githubusercontent.com/1535823/183264601-1564a0ad-0d19-4f28-92c8-6c9d7331a543.png)

But the name used when generating the type provider members (e.g. ` ``Season calendar`` `) don't have this suffix, so the lookup fails.

I didn't look at the code too much, but this line in particular looks fishy: https://github.com/fsprojects/FSharp.Data/blob/6757c40cbd074cb27d227720ef3ad729fe22c2bd/src/Html/HtmlRuntime.fs#L114  
It looks like a special case just for wikipedia, but maybe wikipedia changed their format a little bit...

I don't have time right now to go to the bottom of this issue, but hopefully all this info will give someone a head start to fix it...

**Comment by dsyme** [comment]
Fixed, but only by going direct to Wikipedia

(Unfortunately the Wikipedia HTML changed and the HtmlProvider now puts "Edit" at the end of each section/table name, That's life with this particular type provider :) )
