### ISSUE TITLE
Do we really want inferPrimitiveType API public?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data#1458]
The JsonAnonymizer.fsx sample uses the public `inferPrimitiveType` API.  

However do we seriously want this API public?  I get that making the inference engines used by the type providers available is interesting advanced scenarios, but the API is not currently really designed as a public-facing API, including names like `InferenceMode'`

I vote for removing this sample and making the API internal, for long-term sustainability.

**Comment by cartermp** [comment]
Since we're considering a package split, we can probably do this too and cut a major release, yeah

**Comment by dsyme** [comment]
I've marked it Obsolete
