### ISSUE TITLE
Question: an F# type provider backed by ML.NET for AI/learning

### ISSUE THREAD

**Issue by jkone27** [fsprojects/FSharp.Data#1473]
this is not a real issue, just an idea. Was thinking if it could makes any sense to have a type provider infer some kind of data schema from trained ml models...

https://dotnet.microsoft.com/en-us/apps/machinelearning-ai/ml-dotnet

**Comment by cartermp** [comment]
I don't think that should be a goal of this project. Unclear what it would even mean.
