### ISSUE TITLE
Requesting a new beta package published to nuget.org

### ISSUE THREAD

**Issue by cdituri** [fsprojects/FSharp.Data#1479]
Requesting the publish of a new -beta release to nuget.org

The latest beta available, as of March 29, 2023, is [6.0.1-beta002](https://www.nuget.org/packages/FSharp.Data/6.0.1-beta002) at SHA dae308988c1ae43368508ec65e2ce4c58b59406a. However it does not include recent changes which fix reading CSV from non-seekable network stream, 1e4cb268c2aacfe32a6c4ee8db29552108f5b7f8. These changes are something I require, and for corporate proxy, etc reasons, cannot simply build and consume myself.

Would a newer beta release and publish be possible? Thank you and appreciate what you all do!

**Comment by cartermp** [comment]
One it, going to push a new one today.

**Comment by cartermp** [comment]
New packages up today: https://www.nuget.org/packages/FSharp.Data/6.1.0-beta

**Comment by cdituri** [comment]
Thank you @cartermp !
