### ISSUE TITLE
A new FSharp.Data.JsonSaveOptions value needed

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.Data#1482]
If you use production setting (as you should) of `FSharp.Data.JsonSaveOptions.DisableFormatting`
It will create a following JSON:
{"url":"https://google.com","prop":"x"}

...which looks correct to me, but as you can see, the major automatic parsers like GitHub, Google, Microsoft, etc fail to end the url link to the end-quote, and treat the URL as combining all the rest of the stuff going as part of that url. And as you can see, the full url is not working.

If a single space is added after the comma, then behold, the parsers are clever now:
{"url":"https://google.com", "prop":"x"}

If you do FSharp.Data.JsonSaveOptions.None, then there is way too much unnecessary characters for a production system.
Could we consider adding a little bit more serialization options?

**Comment by bonjune** [comment]
https://github.com/fsprojects/FSharp.Data/blob/ef2eda4cb33386335e25d03e694668b0af6f0945/src/FSharp.Data.Json.Core/JsonValue.fs#L21-L27

I think we can add `JsonSaveOptions.CompactUriAware` case here?

**Comment by Thorium** [comment]
I would also be ok with having just a single comma after every property if that would be easier.

**Comment by bonjune** [comment]
Do you mean to change the behavior of the current `DisableFormatting` case?
Although I can't imagine if there are any cases that rely upon the current behavior (no space after every comma),
but I think it would be more safe to add a case for your case.
