### ISSUE TITLE
WorldBank provider is broken (their API changed to https)

### ISSUE THREAD

**Issue by pkese** [fsprojects/FSharp.Data#1514]
WorldBank stopped responding to `http` requests, but is responding to `https`.

https://github.com/fsprojects/FSharp.Data/blob/71c95c7264cbda846bb675fe177a639d04b94e67/src/FSharp.Data.DesignTime/WorldBank/WorldBankProvider.fs#L31

The above url needs to change to https.

**Comment by pkese** [comment]
To validate (in case it was a temporal failure):

http:
http://api.worldbank.org/v2/en/country/us;cw;zh;ye/indicator/NY.GDP.MKTP.PP.CD?mrv=1&per_page=550

https:
https://api.worldbank.org/v2/en/country/us;cw;zh;ye/indicator/NY.GDP.MKTP.PP.CD?mrv=1&per_page=550

**Comment by Thorium** [comment]
Yes, the current build fails without this.

**Comment by pkese** [comment]
@dsyme @cartermp any chance of pulling either #1515 or #1516 and making a new release?

We have an issue:
- any code using WorldbankProvider stoped working
- any project using WorldbankProvider stopped compiling
- any code using WorldbankProvider has broken language server based editor tools.

**Comment by dsyme** [comment]
@pkese @Thorium For a new release please bump the release notes, and we can crank the handle (it should basically be automatic)
