### ISSUE TITLE
Revisit the CSV schema annotation syntax

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FSharp.Data#181]
I think it is great to have support for all the different features that we currently have in the `Schema` parameter (they are all useful and make good sense) - but I feel that the current syntax is a bit inconsistent and perhaps confusing (mainly because we did not think about all the possible uses in the first version).

So I'm wondering if we should re-think the syntax. With all the features that are there currently, it might be a bit difficult to use without properly reading the documentation (we have documentation, but who reads that?)
- I was thinking if we could make it more similar to F# syntax when possible. 
- Also, I think I would separate _renaming and reordering_ from _renaming type annotating_ (for example `"Fare=float,PClass->Passenger Class"` currently does reordering and renaming but you can also specify `"",,Passenger Class,,,float"` which is just annotating and renaming, but not reordering)

Perhaps we could have static parameters `ColumnsByOrder` and `ColumnsByName` (the names are not ideal - suggestions welcome!) that let you specify columns of the CSV file by order and name respectively:

```
ColumnsByOrder = <col-order>, .. , <col-order>     (*)
ColumnsByName = <col-name>, .., <col-name>

<col-order> = 
  | <empty>
  | <ident> [: <type>]
  | <type>                                         (**)

<col-name> =
  | <ident> [: <type>][ as <ident>]                (***)
```

I think this covers all the combinations that are currently possible. For the `ColumnsByName`, there is also a question of what do we want to do with columns that are not mentioned explicitly. The current version leaves them as they are (sounds reasonable), but I suppose one might want to remove some of them. I suppose you could do this using something like:

```
  <ident> as _     (to remove <ident>)
  _ as _           (to remove all remaining columns)
```

> (*) If there is fewer items than in CSV, ignore the rest. If there is more, it is an error.
> 
> (**) I think it is unfortunate that distinguishing between `<ident>` and `<type>` is ambiguous. Perhaps we could use `_ : <type>`, but that's not so nice. Suggestions welcome!
> 
> (***) The idea is to have a syntax that resembles F# pattern matching but we do not need to require parentheses around type annotations.

I'm not quite happy with the syntax I'm suggesting, but I think getting closer to some familiar syntax would be good. The renaming is not quite the same thing as `as` in F# but it is "kind of" close. But I quite like using `:` for type annotation and `_` as a wildcard.

(We could keep `Schema` for compatibility reasons too, or just increment the major version number if we decide to change this.)

Any ideas?

PS: This is slightly motivated by my work on F# data frame library where I'd like to use the same syntax for specifying types - and I think that should be close to F# so something like `"Foo : int, Bar : float" looks more appealing.

**Comment by cartermp** [comment]
Closing old issue
