### ISSUE TITLE
Add cursor/zipper to support purely functional updates to JsonValue

### ISSUE THREAD

**Issue by eulerfx** [fsprojects/FSharp.Data#638]
Initial implementation [gist](https://gist.github.com/eulerfx/05010aa035dc52c1feee)

As seen in [argonout.io](http://argonaut.io/doc/zipper/)

Needs nice workflow syntax, perhaps based on [this](http://tomasp.net/blog/tree-zipper-query.aspx/).

**Comment by cartermp** [comment]
Closing old issue

**Comment by gusty** [comment]
FYI: purely functional updates to FSharp.Data's JsonValue is possible using Fleece's Json Lenses:

```
#r "nuget: Fleece.FSharpData,0.10.0"

open Fleece
open Fleece.FSharpData
open Fleece.FSharpData.Lens

let json = JsonValue.Parse ("{\"a\": 100, \"b\": true}")
// val json: FSharp.Data.JsonValue = {  "a": 100,  "b": true }

let updated = over (_jkey "a" << _JNumber) (fun x -> x + 10M) json
// val updated: FSharp.Data.JsonValue = {  "a": 110,  "b": true }
```

Other lens operatios currently supported are `view`, `preview` and `setl`.

Hope this helps.
