### ISSUE TITLE
Json Parser upgrade?

### ISSUE THREAD

**Issue by mrange** [fsprojects/FSharp.Data#864]
Hi.

During summer I have been working on an F# JSON parser with my goals of being 100% conforming as well as having decent performance. In addition parser failures should produce good error messages telling the user not only where it fails but also what was expected or unexpected.

During my performance testings I found the parser to compare favorable to JSON.NET as well as FSharp.Data.

A thought struck me, would a more conforming and faster parser be of interest to FSharp.Data.

I did some experimentations of incorporating the parser into FSharp.Data and I got these performance numbers:

```
Using *CURRENT* parser to parse JSON document 1000 times...
  GitHub.json - 764 ms
  WorldBank.json - 182 ms
  allfalse.json - 67 ms
  allnull.json - 56 ms
  allnumber.json - 1656 ms
  allstring.json - 200 ms
  alltrue.json - 66 ms
  charrefs-full.json - 1788 ms
  charrefs.json - 1485 ms
  topic.json - 1513 ms
Using *NEW* parser to parse JSON document 1000 times...
  GitHub.json - 383 ms
  WorldBank.json - 132 ms
  allfalse.json - 57 ms
  allnull.json - 48 ms
  allnumber.json - 206 ms
  allstring.json - 159 ms
  alltrue.json - 56 ms
  charrefs-full.json - 1235 ms
  charrefs.json - 1079 ms
  topic.json - 803 ms
```

We see the performance improvement goes somewhere between 30% to 100% for realistic documents (all\* documents are used to test specific parts of the parser)

In addition `dotTrace` reports that the proposed parser allocates 1/3 memory during test runs, 1600 MB compared to 4600 MB.

Another benefit is decent error messages ie:

```
Failed to parse input as JSON
{"x":3.0,"y":}
-------------^ Pos: 13
Expected: '"', '-', '[', '{', digit, false, null or true
```

Now for potential problems with upgrading the parser:
1. Culture - The proposed parser doesn't support parsing numbers using a provided culture (the JSON spec says nothing of such AFAIK and it's problematic as the decimal delimiter is , in some cultures colliding with the list delimiter in JSON).
2. Sample - The proposed parser doesn't support parsing partially correct documents
3. Fault-tolerance - proposed parser doesn't support fault-tolerant mode
4. Numbers - As JSON is JavaScript specific and JavaScript uses double for number representation the proposed parser only supports doubles (but I am more and more leaning towards decimal as then the parsing of numbers will be "lossless")
5. Numbers - The proposed parser doesn't support trying to parse numbers as currency.

So as there are some differences which may introduce regressions. I would therefore be tempted to provide the parser as an alternative for the users that are after conformance and performance.

If you find this interesting you can check my [branch](https://github.com/mrange/FSharp.Data/tree/mrange/json_perf). The parser is migrated and I run it through some of the test cases but it's most certainly a "Work In Progress" right now.

If you don't find it interesting then no problem.

**Comment by ovatsus** [comment]
I think it would be ok to replace the parser entirely. There was an original parser from @forki, and it had some perf issues, and then we replaced it from the one in the Freebase provider from @dsyme which was faster. Then there were a couple of refactorings and fixes, so the number parsing uses the common methods from TextConversions, which creeped in the culture support. Looking back I think those methods when called from the json parser should always pass the invariant culture and potentially a strict mode flag so stuff like support for currency symbols is disabled.
I do think that we should still use decimal by default, as it's safer, and only use double when it doesn't fit in a decimal, as happens currently.

The Sample was something added to support parsing samples in the ApiaryProvider, I'd also be ok with dropping that.

What do you mean by Fault-tolerance?

This of course would have to bump the version to 3.0 because it's breaking compat, so I'd probably take the opportunity to do a couple of more breaking changes which means I'd take a bit of time before merging this

**Comment by mrange** [comment]
Ok, that sounds like a way forward.

By Fault-tolerance I meant the flag that allows trailing commas (and other things? Perhaps it's the same as the sample flag)

A thing I am considering is to add to the test suite a reference JSON parser that the actual JSON parser can be compared against. I found that very helpful when testing both positive and negative test cases. My current reference parser is written in FParsec which would add that dependency to the test suite (but *not* to the release binaries)

**Comment by ovatsus** [comment]
Oh yes, that's the same as the sample. It's fine to add dependencies to the tests. You can even add Json.Net which has became the de facto parser in .NET

**Comment by mrange** [comment]
Begun replacing the existing parser to see what happens with the test cases, not too bad result so far but of course work remains (mainly wrt to pretty printing/parsing of decimals it seems)

Noticed another regression, previous parser supported \U1234 as unicode character, JSON seems only to support lowercase \u.

**Comment by ovatsus** [comment]
That was a recent fix, as json documents from DbPedia had them, check the history of the file

**Comment by jack-pappas** [comment]
Please also consider using Jil, it's very fast for parsing/serializing. It doesn't support some of the features @mrange suggested, but could be made to with a little work.

**Comment by ovatsus** [comment]
Hi @mrange, are you still interested in doing this?

**Comment by cartermp** [comment]
closing old issue
